apiVersion: v2
name: incident-management
description: A simple CAP project.
type: application
version: 1.0.0
appVersion: 1.0.0
annotations:
  app.kubernetes.io/managed-by: cds-dk/helm
dependencies:
  - name: web-application
    alias: srv
    version: ">0.0.0"
  - name: service-instance
    alias: html5-apps-repo-host
    version: ">0.0.0"
  - name: content-deployment
    alias: html5-apps-deployer
    version: ">0.0.0"
  - name: service-instance
    alias: destination
    version: ">0.0.0"
  - name: service-instance
    alias: hana
    version: ">0.0.0"
  - name: content-deployment
    alias: hana-deployer
    version: ">0.0.0"
  - name: content-deployment
    alias: ams-policies-deployer
    version: ">0.0.0"
  - name: service-instance
    alias: identity
    version: ">0.0.0"
